services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: eraser_user
      POSTGRES_PASSWORD: eraser_pass
      POSTGRES_DB: eraser_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
